#!/usr/bin/env python3
"""Generate SolarOS package configuration from a flavor TOML file."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
import tomllib


PACKAGES = ("core", "audio", "net", "media", "games", "python", "lua", "utils")


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def cmake_string(value: str | Path) -> str:
    text = str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace(";", "\\;") + '"'


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def load_flavor(path: Path) -> tuple[str, str, dict[str, bool]]:
    with path.open("rb") as file:
        data = tomllib.load(file)

    flavor = data.get("flavor", {})
    packages = data.get("packages", {})
    name = str(flavor.get("name") or path.stem)
    description = str(flavor.get("description") or "")
    enabled = {name: bool(packages.get(name, False)) for name in PACKAGES}
    enabled["core"] = True

    unknown = sorted(set(packages) - set(PACKAGES))
    if unknown:
        raise ValueError(f"unknown package key(s): {', '.join(unknown)}")
    if enabled["python"]:
        enabled["net"] = True
    return name, description, enabled


def generate_header(name: str, description: str, enabled: dict[str, bool], source: Path) -> str:
    enabled_names = [pkg for pkg in PACKAGES if enabled[pkg]]
    lines = [
        "/* Generated by scripts/generate_flavor_config.py. Do not edit. */",
        "#pragma once",
        "",
        f"#define SOLAR_OS_FLAVOR_NAME {c_string(name)}",
        f"#define SOLAR_OS_FLAVOR_DESCRIPTION {c_string(description)}",
        f"#define SOLAR_OS_FLAVOR_FILE {c_string(str(source))}",
        f"#define SOLAR_OS_PACKAGE_LIST {c_string(' '.join(enabled_names))}",
        "",
    ]
    for pkg in PACKAGES:
        macro = f"SOLAR_OS_PACKAGE_{pkg.upper()}"
        lines.append(f"#define {macro} {1 if enabled[pkg] else 0}")
    lines.append("")
    return "\n".join(lines)


def generate_cmake(name: str, description: str, enabled: dict[str, bool], source: Path) -> str:
    lines = [
        "# Generated by scripts/generate_flavor_config.py. Do not edit.",
        f"set(SOLAR_OS_FLAVOR_NAME {cmake_string(name)})",
        f"set(SOLAR_OS_FLAVOR_DESCRIPTION {cmake_string(description)})",
        f"set(SOLAR_OS_FLAVOR_FILE {cmake_string(source)})",
    ]
    for pkg in PACKAGES:
        lines.append(f"set(SOLAR_OS_PACKAGE_{pkg.upper()} {1 if enabled[pkg] else 0})")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--header", required=True, type=Path)
    parser.add_argument("--cmake", required=True, type=Path)
    args = parser.parse_args()

    try:
        name, description, enabled = load_flavor(args.input)
        write_if_changed(args.header, generate_header(name, description, enabled, args.input))
        write_if_changed(args.cmake, generate_cmake(name, description, enabled, args.input))
    except Exception as exc:
        print(f"generate_flavor_config.py: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
